# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Felix' Blog
email: knorr.felix@gmx.de
description: >- # this means to ignore newlines until "baseurl:"
    A blog about programming, science, and everything else that I might come up
    with.<br>
    <a href="https://tinyletter.com/KnorrFG">
        Subscribe for notification mails when I publish a new post</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://knorrfg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/logo.png"
locale: "en-us"
mathjax: true
# search_full_content: true
category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"
disqus:
      shortname: knorrfg-github-io
#twitter_username: jekyllrb
github_username: KnorrFG
# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"
# theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#

defaults:
    - scope: 
          path: "_posts" # an empty string here means all files in the project 
          type: "posts" # previously `post` in Jekyll 2.2.  
      values:
          author:
              name: Felix G. Knorr
          layout: post
          share: true

footer_links:
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square
  - title: Subscribe for updates by mail
    url: https://tinyletter.com/KnorrFG
    icon: fas fa-envelope
